apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop-cart
  name: eshop-cart
spec:
  type: NodePort
  ports:
    - port: 80
      name: "80"
      targetPort: 6000
      nodePort: 32766
  selector:
    app: eshop-cart
