apiVersion: v1
kind: Service
metadata:
  name: eshop-cart-service
  labels:
    app: eshop-cart-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: "80"
      targetPort: 5000
      nodePort: 32765
  selector:
    app: eshop-cart
